version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        volumes:
            - ./jekyll:/srv/jekyll
        command: >
            bash -c "jekyll build
            && jekyll serve --watch --force_polling"
        ports: 
            - "4000:4000"
    bokeh:
        build:
            context: .
            dockerfile: ./compose/local/bokeh/Dockerfile
        # This said data_to_map_image and I'm not sure what it meant
        image: bokeh_image
        volumes:
            - ./bokeh:/srv/bokeh
            - ./jekyll:/srv/jekyll
        command: python -u bokeh/vis.py
